version: '3.1'

volumes:
  db:

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db:db
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: example